build:
  version: "3.0"

accounts:
  message: "Welcome to MiniBank accounts related local APIs "
  contactDetails:
    name: "Mahmoud Mehisen - Software Engineer"
    email: "mahmoudmehisen@minibank.com"