spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MiniBank accounts related local APIs "
  contactDetails:
    name: "Mahmoud Mehisen - Software Engineer"
    email: "mahmoudmehisen@minibank.com"